apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xu2h2dhys-python
  janus-idp.io/tekton: xu2h2dhys-python
  backstage.io/kubernetes-id: xu2h2dhys-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xu2h2dhys-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
