apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xu2h2dhys-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xu2h2dhys-python 
  name: xu2h2dhys-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xu2h2dhys-python 
